using System.Collections;
using UnityEngine;
using UnityEngine.TestTools;
using Unity.AutomatedQA;
using Unity.CloudTesting;

namespace GeneratedAutomationTests
{
    /// <summary>
    /// These tests were generated by Unity Automated QA for the recording from the Assets folder at "\Recordings\start_game.json".
    /// You can regenerate this file from the Unity Editor Menu: Automated QA > Generate Recorded Tests
    /// </summary>
    public class Tests_start_game : AutomatedQATestsBase
    {
        /// Generated from recording file: "\Recordings\start_game.json".
        [UnityTest]
        [CloudTest]
        public IEnumerator CanPlayToEnd()
        {
            yield return Driver.Perform.Click(Scene_MainMenu_PageObject.Clickable_MainMenu_Start);
        }
        // Initialize test run data.
        protected override void SetUpTestRun()
        {
            Test.entryScene = Scene_MainMenu_PageObject.SceneName;
            Test.recordedAspectRatio = new Vector2(1128f,623f);
            Test.recordedResolution = new Vector2(1920f,1080f);
        }

    }
}
