name: UnityPipeline

on:
  push:
  workflow_dispatch:
    inputs:
      target_platform:
        description: 'Target Platform'
        required: true
        default: 'StandaloneWindows64'
        type: choice
        options:
          - StandaloneWindows64
          - StandaloneLinux64
          - WebGL
      run_tests:
        description: 'Run PlayMode tests'
        required: true
        default: true
        type: boolean
      run_build:
        description: 'Run project build'
        required: true
        default: true
        type: boolean
      create_release:
        description: 'Create GitHub release'
        required: true
        default: true
        type: boolean

permissions:
  contents: write
  pull-requests: write
  checks: write
  pages: write
  id-token: write

env:
  PROJECT_PATH: .
  BUILD_NAME: UnityBuild
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  UNITY_EMAIL:    ${{ secrets.UNITY_EMAIL }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

jobs:
  unity_ci:
    name: Tests, Build, Artifacts, Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 1

      - name: Debug - Check disk usage before cleanup
        run: |
          echo "### Disk Usage Before Cleanup" >> $GITHUB_STEP_SUMMARY
          df -h >> $GITHUB_STEP_SUMMARY
          docker system df || true >> $GITHUB_STEP_SUMMARY

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          android: true
          haskell: true
          large-packages: true
          docker-images: false
          swap-storage: false
          dotnet: false
          tool-cache: false

      - name: Debug - Check disk usage after cleanup
        run: |
          echo "### Disk Usage After Cleanup" >> $GITHUB_STEP_SUMMARY
          df -h >> $GITHUB_STEP_SUMMARY
          docker system df || true >> $GITHUB_STEP_SUMMARY

      - name: Cache Library
        uses: actions/cache@v4
        with:
          path: ${{ env.PROJECT_PATH }}/Library
          key: Library-${{ runner.os }}-Unity${{ steps.unity.outputs.version }}-${{ hashFiles(format('{0}/Packages/manifest.json', env.PROJECT_PATH)) }}-${{ hashFiles(format('{0}/Packages/packages-lock.json', env.PROJECT_PATH)) }}
          restore-keys: |
            Library-${{ runner.os }}-Unity${{ steps.unity.outputs.version }}-

      - name: Set mode flags
        id: mode
        shell: bash
        run: |
          # Defaults
          run_tests="true"
          run_build="true"
          create_release="true"
          target_platform="StandaloneWindows64"

          echo "run_tests=${run_tests}"        >> $GITHUB_OUTPUT
          echo "run_build=${run_build}"        >> $GITHUB_OUTPUT
          echo "create_release=${create_release}" >> $GITHUB_OUTPUT
          echo "target_platform=${target_platform}" >> $GITHUB_OUTPUT

      - name: Hard-unset Unity activation envs
        run: |
          echo "UNITY_SERIAL="   >> "$GITHUB_ENV"

      - name: Detect UNITY_* envs
        run: |
          set -euo pipefail
          for v in UNITY_LICENSE UNITY_SERIAL UNITY_EMAIL UNITY_PASSWORD; do
            if [[ -v $v ]]; then
              eval "val=\${$v}"
              echo "$v is SET (len=${#val})"
            else
              echo "$v is NOT set"
            fi
          done
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

      - name: Debug - List project directory before any runs
        run: |
          echo "### Project Directory Structure Before Runs" >> $GITHUB_STEP_SUMMARY
          ls -R ${{ env.PROJECT_PATH }} >> $GITHUB_STEP_SUMMARY
          echo "=== Finding Settings.json ==="
          find ${{ env.PROJECT_PATH }} -name "Settings.json" -type f

      - name: Debug - Print Code Coverage Settings File
        run: |
          SETTINGS_PATH="${{ env.PROJECT_PATH }}/ProjectSettings/Packages/com.unity.testtools.codecoverage/Settings.json"
          if [ -f "$SETTINGS_PATH" ]; then
            echo "### Code Coverage Settings.json Content" >> $GITHUB_STEP_SUMMARY
            cat "$SETTINGS_PATH" >> $GITHUB_STEP_SUMMARY
          else
            echo "Settings.json not found at $SETTINGS_PATH" >> $GITHUB_STEP_SUMMARY
          fi

      - name: Build
        if: steps.mode.outputs.run_build == 'true'
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE:  ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL:    ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: ${{ env.PROJECT_PATH }}
          targetPlatform: ${{ steps.mode.outputs.target_platform }}
          buildName: ${{ env.BUILD_NAME }}

      - name: Debug - List project directory after build
        if: steps.mode.outputs.run_build == 'true'
        run: |
          echo "### Project Directory After Build" >> $GITHUB_STEP_SUMMARY
          ls -R ${{ env.PROJECT_PATH }} >> $GITHUB_STEP_SUMMARY 2>&1 || true

      - name: Upload Build Artifact
        if: success() && steps.mode.outputs.run_build == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ steps.mode.outputs.target_platform }}
          path: build/**/*
          retention-days: 30

      - name: Ensure artifacts dirs
        run: mkdir -p artifacts/performance artifacts/CodeCoverage

      - name: Run PlayMode Tests
        id: tests
        if: steps.mode.outputs.run_tests == 'true'
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE:  ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL:    ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: ${{ env.PROJECT_PATH }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          testMode: PlayMode
          artifactsPath: artifacts
          coverageOptions: generateAdditionalMetrics;generateHtmlReport;generateHtmlReportHistory;generateBadgeReport;assemblyFilters:+Assembly-CSharp,+GeneratedTests,+PlayMode,+Scripts,+StarterAssets
          coverageResultsPath: artifacts/CodeCoverage
          customParameters: >
            -debugCodeOptimization
            -burst-disable-compilation
            -enableCodeCoverage
            -testCategory "!SkipCI"
            -testResults artifacts/test-results.xml
            -perfTestResults artifacts/performance/perf-results.json
            -enableProfiler
            -v

      - name: Debug - List all directories and files after tests
        if: always() && steps.mode.outputs.run_tests == 'true'
        run: |
          echo "### Full Workspace Directory Structure After Tests" >> $GITHUB_STEP_SUMMARY
          ls -R . >> $GITHUB_STEP_SUMMARY 2>&1 || true
          echo "### Project Path Contents" >> $GITHUB_STEP_SUMMARY
          ls -R ${{ env.PROJECT_PATH }} >> $GITHUB_STEP_SUMMARY 2>&1 || true
          echo "### Artifacts Directory Contents" >> $GITHUB_STEP_SUMMARY
          ls -R artifacts >> $GITHUB_STEP_SUMMARY 2>&1 || true
          echo "### CodeCoverage Directory if exists" >> $GITHUB_STEP_SUMMARY
          ls -R ${{ env.PROJECT_PATH }}/CodeCoverage >> $GITHUB_STEP_SUMMARY 2>&1 || echo "No CodeCoverage in project root"
          ls -R artifacts/CodeCoverage >> $GITHUB_STEP_SUMMARY 2>&1 || echo "No CodeCoverage in artifacts"
          echo "### Finding all XML files" >> $GITHUB_STEP_SUMMARY
          find . -name "*.xml" >> $GITHUB_STEP_SUMMARY 2>&1 || true
          echo "### Finding all HTML files" >> $GITHUB_STEP_SUMMARY
          find . -name "*.html" >> $GITHUB_STEP_SUMMARY 2>&1 || true
          echo "### Finding all OpenCover files" >> $GITHUB_STEP_SUMMARY
          find . -name "*.opencover.xml" >> $GITHUB_STEP_SUMMARY 2>&1 || true
          echo "### Finding all coverage-related files" >> $GITHUB_STEP_SUMMARY
          find . -name "*coverage*" -o -name "*Coverage*" -o -name "*CodeCoverage*" >> $GITHUB_STEP_SUMMARY 2>&1 || true
          echo "### Test Runner Outputs" >> $GITHUB_STEP_SUMMARY
          echo "Artifacts Path: ${{ steps.tests.outputs.artifactsPath }}" >> $GITHUB_STEP_SUMMARY
          echo "Coverage Path: ${{ steps.tests.outputs.coveragePath }}" >> $GITHUB_STEP_SUMMARY
          echo "Test Results Path: ${{ steps.tests.outputs.resultsPath }}" >> $GITHUB_STEP_SUMMARY

      - name: Debug - Print sample coverage file contents if exists
        if: always() && steps.mode.outputs.run_tests == 'true'
        run: |
          COVERAGE_XML=$(find artifacts -name "*.opencover.xml" -print -quit 2>/dev/null)
          if [ -n "$COVERAGE_XML" ]; then
            echo "### Sample Coverage XML Head (first 50 lines)" >> $GITHUB_STEP_SUMMARY
            head -n 50 "$COVERAGE_XML" >> $GITHUB_STEP_SUMMARY
          else
            echo "No *.opencover.xml found" >> $GITHUB_STEP_SUMMARY
          fi
          REPORT_INDEX=$(find artifacts -name "index.html" -print -quit 2>/dev/null)
          if [ -n "$REPORT_INDEX" ]; then
            echo "### Coverage Report Index.html exists at $REPORT_INDEX" >> $GITHUB_STEP_SUMMARY
          else
            echo "No index.html found in coverage reports" >> $GITHUB_STEP_SUMMARY
          fi

      - name: Parse Performance Results
        if: always() && steps.mode.outputs.run_tests == 'true'
        run: |
          set -euo pipefail
          sudo apt-get update -y && sudo apt-get install -y jq
      
          JSON_PATH="artifacts/performance/perf-results.json"
          if [ ! -f "$JSON_PATH" ]; then
            echo "No performance test results found (missing $JSON_PATH)" >> "$GITHUB_STEP_SUMMARY"
            exit 0
          fi
      
          {
            echo "## Performance Test Summary"
            echo
            echo "| Test | Metric | Median | Unit | FPS |"
            echo "|---|---|---:|---|---:|"
      
            jq -r '
              def unit_name($u):
                (["Nanosecond","Microsecond","Millisecond","Second",
                  "Byte","Kilobyte","Megabyte","Gigabyte","Undefined"][$u] // "Unknown");
      
              # choose root: .Results (3.1+), else .Tests, else array
              (if (.Results? | type=="array") then .Results
               elif (.Tests? | type=="array") then .Tests
               elif (type=="array") then .
               else [] end)
              | .[]
              | .Name as $test
              | (.SampleGroups // [])[]
              | . as $g
              | [
                  $test,
                  ($g.Name // "unknown"),
                  ($g.Median // $g.Average // $g.Min // "n/a"),
                  (if ($g.Unit|type)=="number" then unit_name($g.Unit) else ($g.Unit // "n/a") end),
                  (if (($g.Name=="Time") and (($g.Median // 0) > 0))
                     then (1000/($g.Median)) else empty end)
                ]
              | @tsv
            ' "$JSON_PATH" \
            | awk -F'\t' '{
                test=$1; metric=$2; med=$3; unit=$4; fps=$5;
                if (fps=="") printf("|%s|%s|%s|%s| |\n", test, metric, med, unit);
                else          printf("|%s|%s|%.2f|%s|%.1f|\n", test, metric, med, unit, fps);
              }'
          } >> "$GITHUB_STEP_SUMMARY"

      - name: Upload Test Results (XML, logs, coverage)
        if: always() && steps.mode.outputs.run_tests == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: unity-test-results
          path: |
            artifacts/**/*.xml
            artifacts/**/*.log
            artifacts/performance/**/*.html
            artifacts/performance/**/*.json
            **/Logs/**
            **/CodeCoverage/**
            artifacts/CodeCoverage/**
            Coverage/**
          retention-days: 14

      - name: Debug - After Upload, confirm artifact paths
        if: always() && steps.mode.outputs.run_tests == 'true'
        run: |
          echo "### Paths Included in Upload Artifact" >> $GITHUB_STEP_SUMMARY
          echo "artifacts/**/*.xml" >> $GITHUB_STEP_SUMMARY
          find artifacts -name "*.xml" >> $GITHUB_STEP_SUMMARY 2>&1 || true
          echo "artifacts/**/*.log" >> $GITHUB_STEP_SUMMARY
          find artifacts -name "*.log" >> $GITHUB_STEP_SUMMARY 2>&1 || true
          echo "**/Logs/**" >> $GITHUB_STEP_SUMMARY
          find . -path "*/Logs/*" >> $GITHUB_STEP_SUMMARY 2>&1 || true
          echo "**/CodeCoverage/**" >> $GITHUB_STEP_SUMMARY
          find . -path "*/CodeCoverage/*" >> $GITHUB_STEP_SUMMARY 2>&1 || true
          echo "artifacts/CodeCoverage/**" >> $GITHUB_STEP_SUMMARY
          find artifacts/CodeCoverage >> $GITHUB_STEP_SUMMARY 2>&1 || true
          echo "Coverage/**" >> $GITHUB_STEP_SUMMARY
          find . -path "*/Coverage/*" >> $GITHUB_STEP_SUMMARY 2>&1 || true

      - name: Publish Test Results
        if: always() && steps.mode.outputs.run_tests == 'true'
        uses: dorny/test-reporter@main
        with:
          name: Unity PlayMode Tests
          path: 'artifacts/test-results.xml'
          reporter: dotnet-nunit
          fail-on-error: false

      - name: Create GitHub Release
        if: success() && steps.mode.outputs.run_build == 'true' && steps.mode.outputs.create_release == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: unity-build-${{ github.run_number }}
          name: Unity Build ${{ github.run_number }}
          body: |
            Automated Unity build from commit ${{ github.sha }}
            **Platform:** ${{ steps.mode.outputs.target_platform }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy_coverage:
    name: Publish Coverage to GitHub Pages
    needs: unity_ci
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Download coverage artifact
        uses: actions/download-artifact@v4
        with:
          name: unity-test-results
          path: coverage-artifact

      - name: Debug - List all files in coverage artifact
        run: |
          echo "### Listing all files in coverage artifact" >> $GITHUB_STEP_SUMMARY
          find coverage-artifact -type f >> $GITHUB_STEP_SUMMARY 2>&1 || true
          echo "### Listing directories" >> $GITHUB_STEP_SUMMARY
          find coverage-artifact -type d >> $GITHUB_STEP_SUMMARY 2>&1 || true
          echo "### Finding HTML files" >> $GITHUB_STEP_SUMMARY
          find coverage-artifact -name "*.html" >> $GITHUB_STEP_SUMMARY 2>&1 || true
          echo "### Finding XML files" >> $GITHUB_STEP_SUMMARY
          find coverage-artifact -name "*.xml" >> $GITHUB_STEP_SUMMARY 2>&1 || true
          echo "### Finding coverage directories" >> $GITHUB_STEP_SUMMARY
          find coverage-artifact -name "*Coverage*" -type d >> $GITHUB_STEP_SUMMARY 2>&1 || true

      - name: Debug - Print sample file contents if coverage files exist
        run: |
          COVERAGE_XML=$(find coverage-artifact -name "*.opencover.xml" -print -quit 2>/dev/null)
          if [ -n "$COVERAGE_XML" ]; then
            echo "### Sample Coverage XML Head" >> $GITHUB_STEP_SUMMARY
            head -n 50 "$COVERAGE_XML" >> $GITHUB_STEP_SUMMARY
          fi
          REPORT_INDEX=$(find coverage-artifact -name "index.html" -print -quit 2>/dev/null)
          if [ -n "$REPORT_INDEX" ]; then
            echo "### Coverage index.html Head" >> $GITHUB_STEP_SUMMARY
            head -n 50 "$REPORT_INDEX" >> $GITHUB_STEP_SUMMARY
          fi

      - name: Try to locate coverage report path
        id: find_coverage
        run: |
          COVERAGE_PATHS=(
            "coverage-artifact/artifacts/CodeCoverage/Report"
            "coverage-artifact/artifacts/CodeCoverage/Results/Report"
            "coverage-artifact/CodeCoverage/Results/Report"
            "coverage-artifact/CodeCoverage/Report"
            "coverage-artifact/Coverage/Report"
            "coverage-artifact/artifacts/CodeCoverage"
            "coverage-artifact/CodeCoverage"
            "coverage-artifact/Coverage"
            "coverage-artifact/artifacts"
            "coverage-artifact"
          )
          
          REPORT_PATH=""
          for path in "${COVERAGE_PATHS[@]}"; do
            if [ -d "$path" ] && [ -n "$(find "$path" -name "*.html" -type f)" ]; then
              echo "Found coverage report at: $path" >> $GITHUB_STEP_SUMMARY
              REPORT_PATH="$path"
              break
            fi
          done
          
          if [ -z "$REPORT_PATH" ]; then
            echo "Could not find coverage report in expected locations" >> $GITHUB_STEP_SUMMARY
            REPORT_PATH=$(find coverage-artifact -type f -name "*.html" -exec dirname {} \; | head -1 | uniq)
            if [ -n "$REPORT_PATH" ]; then
              echo "Fallback: Found HTML files in: $REPORT_PATH" >> $GITHUB_STEP_SUMMARY
            else
              echo "No HTML files found anywhere in artifact" >> $GITHUB_STEP_SUMMARY
              exit 1
            fi
          fi
          
          echo "REPORT_PATH=$REPORT_PATH" >> $GITHUB_ENV
          echo "report_path=$REPORT_PATH" >> $GITHUB_OUTPUT

      - name: Upload Pages artifact
        if: env.REPORT_PATH != ''
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.REPORT_PATH }}

      - name: Deploy to GitHub Pages
        id: deploy
        if: env.REPORT_PATH != ''
        uses: actions/deploy-pages@v4

      - name: Add link to summary
        if: always()
        run: |
          echo "### Code Coverage Deployment" >> "$GITHUB_STEP_SUMMARY"
          if [ "${{ steps.deploy.outcome }}" == "success" ]; then
            echo "Latest report: ${{ steps.deploy.outputs.page_url }}" >> "$GITHUB_STEP_SUMMARY"
          else
            echo "Failed to deploy coverage report. Check debug logs above." >> "$GITHUB_STEP_SUMMARY"
            echo "Report path attempted: ${{ env.REPORT_PATH }}" >> "$GITHUB_STEP_SUMMARY"
          fi
